dist: trusty
env:
  matrix:
  - MOZ_HEADLESS=1
  global:
  - secure: 0/fiRdhYejVC5H/FChvQ2C9QxMCpwr2F6dcbk5unbNZmJAs6cN1L9yg4Zcnj9Ec8Jqnb24bNu2ZkOKqy+Fx5ZMF1ox6wWByZd5Bq7T6I61jRL4Wn0Jj4I8ewv7Ud9rT8M86lJFBqo2UATiKrYUcmuVrKip95GvDqud8+kYic9Z/4rJO4nn+dbCsNICI7j/kP5YIzhawFC3DORLUZl6Kqa1D/kilt0DfRqDD6i345HaTFc+e8z+jv4XHwONbPI4SWPzqCGnnD6Kl7fQU+8hqq8DXek68KghQQFPsWoA7eoenfwgzJIXUAQChMqyyK7knjFEmpZPNBJBWkwZHgKwn0cdO/kHnollCJX8Sr9rgzAyVUytRVux5yO3LkPNvuxGiuvweKJDO+f0grDCVW4xkIRX9CN5Nf+Cr+SDJ/UaQcSZU+1Zql9u91J8H6W7162unrxs+EcG2kS3m39M6BDo4TVJ/IgNDcuJNlM+Kg/jJIsKXtQihyKjRbMJpFuXLf7kLH4BYUFymS6yl1SNi7R2iRnZqndHRPAOFghJ5OZZUWG40XbzsAz0kqnaCKoP6xwLfuQO5Jz9no3bMLAbGMnaj0jwJJcKgwZWToX0xhPwu6/K9AoxPfreD5cu+Sxw/0cRfqH0kEd9Fi0PfVCO/epNGygW792M1GKbxlNaMO7GBsBK8=
  - secure: HteQ3KkiwNNylix/ZYu7SNI7dn+O/1mQSOOY9faFYonXp/ay8JslqJD6h6X+vXS36ZwjdCLivslxu98B1UkS5zVHrbnHSRpHQreV6PlDmKhV4seUOSuW9YA2ySpDaBuZWYeL+FPWJce7Xos/6hmZv3hz513NiNz4Syih/v5akoNGxiDreJw38gIxJJdDWGDfUo5WZ6ZpfXDINdl410hvKUB+7dIwmcfaaOTqqYc2wpcV+OtS/kzqjtkgaLkpKzLagVv2Dul7VqEdU7WemZ1LXftQFg59JXVt9q58nVLWw5cG2dAfOz3WldtOL2SqWqumRYYW6IeYSGY0cGzArN16sz9AtaWWaxi1UBnn4mCKOpGoejgc1t3r6EC4oQz4b0WpUaf7XPcOTZ5shjEVDu8HX+Yrt2g5tM/jI0S2jqMxRXoNFCEDIl+nnNSdOC9ErA6PuBQstLoAc6/r/Z5TLxNsSSZYIgyVH8JX1wmbioubN1imhM8dTn7mH6gayS5vfn8wOWy+zSk75rZHH6WIv+xVTXdb9XdnlFaZkgS35R0pkCgSuf5fia792umPzdTS0pMssvX/J3sOM4ZqhcQn951z7PziKVfMm8Xrh1kfSb9EKAV5yYHZ6k0My8H7ERjCufp99qpFt4ayOTDjzn5dMXcnt/Y5bYAtxrCtsDJyoItZtyY=
  - secure: 2QTU3tp5+EY8y/d46iz7i1BqM5fuq0ZvdBnvpumP+8A6WTbqgCkim0b9ehhNyhWEwhEmIkT/LppJ6Ut6lNeeGL7bvDqKMX+nokJaUA1aM6TA7QF9nhqFoKWFaJIyzZyysKvVlD2XDVKCpm10Be5QY9mCP6NDpZNcxXetqObv58kjMAQXnvdfPOOs0SHABq91KiYKxTshV9MHdmZWP/AvTMjTy7anVvfRNTvq+p8Ke0KJaVxUI3UrWzB2LtzQSs9GrlDu7bAvThYthTaYAiDgM1b5oOSK2avT8N4Q+dfMraYINZhPVgupzeNGBGDjr2KB/J+GImc6cMzeQ0mtAAErYvo+NyDIGpV5naEtBNQmuzCknDroW+6YWfXeKNpW63Ve9KGSG9KjLWlXB+vO++Eg9m4s6sPE79shzS+w0DT74c9PEHmBZ6Sj0VSpesL/eadkmVGFaR1tsXDFyycVq+EwBIHfNCv4RlmKNCfBEUdFBYcC0TvsFQh46NNXI0Bx8cnPmf/QY9Gz44aN2YGVk2+E7UvnfBo0RLeq9/2dVVZEnPeGXiW1Jk+ccOuiDiC4NQLqt5wPyDcPpcWf1D6Ldr6IW95KQgq9EShYTYxuZbOnAtOX+URJePqX77wcBBuPIWpWSfZOWSkvepyaCuAmMbvTB1VGz+QOi8nRl2kkbsy1Rtk=
addons:
  firefox: latest
  chrome: stable
sudo: required
language: java
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
before_script:
- rm -rf target
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis-build-pr.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis-build.sh; fi
